### ISSUE TITLE
Include tests into the PyPI archive

### ISSUE THREAD

**Issue by ignatenkobrain** [gruns/orderedmultidict#12]
please

**Comment by gruns** [comment]
I haven't a clue why tests weren't included in v0.7.7 and v0.7.8. Both of those
release tarballs were generated with the same `python setup.py sdist` that
generated all prior releases, which included tests. No relevant changes to
setup.py were made between v0.7.6 (which includes tests) and v0.7.7 (which
doesn't include tests).

To rectify the lack of tests in v0.7.8, I created a new release for PyPI,
v0.7.10, that includes tests.

I'll keep an eye on this odd regression to make sure future releases correctly
contain tests.

Thank you for bringing this issue to my attention Igor. Don't hesitate to let me
know if there's anything else I can do for you.
