### ISSUE TITLE
Tests fail because __init__.py is missing

### ISSUE THREAD

**Issue by daym** [gruns/orderedmultidict#14]
When trying to run the tests I get:

```python
NotImplementedError: Can't perform this operation for unregistered loader type
```

That's because `tests/__init__.py` is missing.

(It can be just an empty file - but it has to exist)

**Comment by gruns** [comment]
How are you running the tests?

Both nose

```
$ nosetests --exe -x
....................................................
----------------------------------------------------------------------
Ran 52 tests in 0.434s

OK
```

and tox/detox

```
$ detox
...
________________________________________ summary _________________________________________
  codestyle: commands succeeded
  py26: commands succeeded
  py27: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  py35: commands succeeded
  pypy: commands succeeded
  congratulations :)
```

succeed without `__init__.py`. Both locally and on Travis

  https://travis-ci.org/gruns/orderedmultidict

**Comment by daym** [comment]
I'm trying to package it for the Guix distribution. It runs `python3 setup.py test` and that fails.

When I extract orderedmultidict-0.7.10 and run `python3 setup.py test` manually, it fails, too.

**Comment by gruns** [comment]
Does https://github.com/gruns/orderedmultidict/pull/15 restore `python3 setup.py test` for you?

```
$ python3 setup.py test
running test
....................................................
----------------------------------------------------------------------
Ran 52 tests in 0.285s

OK
```

If so, I'll merge.

**Comment by gruns** [comment]
Does https://github.com/gruns/orderedmultidict/pull/15 restore `python3 setup.py test` for you?

```
$ python3 setup.py test
running test
....................................................
----------------------------------------------------------------------
Ran 52 tests in 0.285s

OK
```

If so, I'll merge.

**Comment by daym** [comment]
Yes, it works with that.

**Comment by gruns** [comment]
Awesome.

Fix included in the freshly stamped orderedmultidict v0.7.11.

```python
$ python -c "import orderedmultidict; print orderedmultidict.__version__"
0.7.11
$ python3 setup.py test
running test
....................................................
----------------------------------------------------------------------
Ran 52 tests in 0.281s

OK
```

Thank you again Danny. Don't hesitate to let me know if there's anything else I can do for you.
