### ISSUE TITLE
Upload a Wheel to PyPI

### ISSUE THREAD

**Issue by ghickman** [gruns/orderedmultidict#17]
This package currently has no wheels on PyPI for its latest version, it would be great if it did!  A simple list of benefits can be found [here](https://pythonwheels.com/#advantages).

A guide to building wheels can be found [here](https://pythonwheels.com/#creating-wheels), and a more in-depth, exhaustive guide [here](https://packaging.python.org/guides/distributing-packages-using-setuptools/?highlight=wheel#wheels).

I'd be happy to submit a PR scripting and documenting the packaging step of your releases if that would help?

Thanks!

**Comment by gruns** [comment]
Awesome. Thank you for the links and context, George.

Anything jump out at you as missing from https://github.com/gruns/orderedmultidict/pull/18?

If not, I'll merge and upload away.

**Comment by gruns** [comment]
Code merge and Wheel uploaded.

 * https://pypi.org/project/orderedmultidict/#files

Huge thank you for bringing this issue to my attention, George. Don't hesitate
to let me know if there's anything else I can do for you.

**Comment by jezdez** [comment]
For the record, in case someone finds this issue via Google, this will create a hash mismatch when using [pip hash checking mode](https://pip.pypa.io/en/stable/user_guide/#hash-checking-mode).

**Comment by gruns** [comment]
@jezdez Thank you for the heads up.

Luckily, this issue won't apply in future releases because the Wheel wasn't added to an already published source release.

**Comment by jezdez** [comment]
@gruns Yup! And thank you for enabling it 👍
