### ISSUE TITLE
Please release new version (includes the fix in #20)

### ISSUE THREAD

**Issue by stig** [gruns/orderedmultidict#24]
I am happy that issue #20 was merged, but I'm still seeing issue #19 because there's not been a new release yet on PyPI. Would it be possible to cut a new release please?

**Comment by gruns** [comment]
Huge thank you for the bump here, Stig. v1.0.1 now live on PyPi.

  * https://pypi.org/project/orderedmultidict/

Does updating to v1.0.1 resolve your problem?

**Comment by stig** [comment]
@gruns thanks, it appears it does! Unfortunately it didn't fix my build, but it now breaks on another issue so I can move forward :-)

**Comment by gruns** [comment]
@stig To be explicit, the new issue is unrelated to orderedmultidict, correct?

**Comment by stig** [comment]
@gruns yes, correct!

**Comment by gruns** [comment]
Awesome. Closing this Issue. And crush your project's new, troublesome issue.

Thank you again, Stig. Don't hesitate to let me know if there's anything else I can do for you.
