### ISSUE TITLE
Tag latest release in git

### ISSUE THREAD

**Issue by inakimalerba** [gruns/orderedmultidict#28]
Dear Maintainer,

Would you please tag the latest release on the repository so I can bump the version distributed in Debian cleanly?

Thanks in advance :smile:

**Comment by gruns** [comment]
sure! i will shortly and update this issue once done

**Comment by gruns** [comment]
v1.0.1 tagged! https://github.com/gruns/orderedmultidict/releases/tag/v1.0.1

thank you for opening this issue, @inakimalerba! 🙌
